### ISSUE TITLE
1.8 Error

### ISSUE THREAD

**Issue by Brandowizard** [10becja/ChessCraft#1]
I loaded the plugin and created a game. When it was my move I left clicked the piece and then where I wanted it. Then this error came up: http://pastebin.com/QYy0jPHB  Please fix this, or tell me how I can fix this. This plugin is amazing, and I was super excited when I saw it had been updated. Thanks!

**Comment by 10becja** [comment]
The updated version is for minecraft 1.9.x, not 1.8. I _think_ the version on http://dev.bukkit.org/bukkit-plugins/chesscraft/ will still work on 1.8 however I know my version will not. If you do want to use this version with 1.8, you could try setting the effects section to the 1.8 sounds, which might fix your problem.

```
effects:
    piece_captured: explosion
    piece_selected: sound,name=note_sticks
    piece_unselected: sound,name=note_bass
    piece_moved: sound,name=item_pickup
    check: sound,name=orb_pickup
    game_lost: sound,name=enderman_death
    game_won: sound,name=level_up
    teleport_out: effect,name=smoke,data=4
    teleport_in: effect,name=ender_signal
    piece_riding: true
    volume: 1.0
```

If that doesn't work, or the bukkit version doesn't work with 1.8, please let me know and I'll see if I can add a fix
